# Welcome to Jekyll!
title: Gabriel Rozendo CV
url: CV.Gabriel.Rozendo.dev
baseurl:

# Sass setting
sass/style: compressed

# Privacy
open: true                  # show or hide your resume
allow_search_engines: true  # allow your resume indexing by search engine, 'true' or 'false'
description:  # your resume description
open_graph:
  enable: false                        # enable open graph meta tags
  image: /assets/images/profile.png   # path or link to the open graph image

# Style
date_format: "%d/%m/%Y"     # date format
theme_color: "#000022"      # your favorite theme color
contact_delimiter: "·"      # contact delimiter, '·', '/' or '|'
section_icon: true          # section title icon, true or false
section_title: uppercase    # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
section_align: start        # section title align, 'start', 'end' or 'center'
section_line: dashed        # section title line, 'solid', 'dashed' or 'none'
section_background: false   # section title backound, 'true' or 'false'
skill_level_icon: lightbulb # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
link_icon: true             # show link icon, 'true' or 'false'
site_footer: true           # show site footer, 'true' or 'false'

# Analytics
analytics:
  google:                   # google
  cloudflare:               # cloudflare
  umami:                    # umami
    script: https://u.rozendo.dev/script.js
    website_id: 48951500-3139-4f72-a6c4-873cf85888f2
    domains: cv.gabriel.rozendo.dev,127.0.0.1,localhost
  tianji:
    script: https://tianji.modelviewlabs.com/tracker.js
    website_id: cm4n1js9t1r6wbqpugenm8orn

